# use NodeJS, whatever version
language: node_js
node_js: node

# install yarn
install: yarn
node_js:
  - 12

script:
  # generate the schema, and check that the file exists
  - yarn --silent genschema > src/schema/openmath.json.test && diff src/schema/openmath.json src/schema/openmath.json.test
  # check that the example typecheck
  - yarn test