name: CI

on: [push, pull_request]

env:
  NODE_VERSION: '16'

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check that schema generation still works
        run: |
          yarn --silent genschema > src/schema/openmath.json.test
          diff src/schema/openmath.json src/schema/openmath.json.test
      - name: Run 'yarn test'
        run: yarn test